### ISSUE TITLE
which .efi file should be replaced?

### ISSUE THREAD

**Issue by JiniMaster** [pawitp/grub2-chromiumos-n4200#2]
thanks for your patch. exactly what i would need...

however: you say that "replace either grubx64.efi or bootx64.efi in your EFI partition."
but I cannot find an "EFI" partition on my chromium USB stick. there are multiple partitions and three of them are browse-able with linux...
the only "efi" directory i can find is on the ROOT-A partition: \boot\efi\boot" - with the following files:
* grub.cfg
* bootia32.efi
* bootx64.efi

now - the only file in your "Release" page is "grubx64.efi"...
i tried renaming the existing bootia32.efi & bootx64.efi files to zbootia32.zefi & zbootx64.zefi and copied your grubx64.efi file to the directory. (I later even deleted the two origninal .efi files)
but when i try to boot from the USB-stick there's still the same issue as before: black screen with white caret on top-left screen?!

...any ideas?
thanks!

**Comment by pawitp** [comment]
You need to manually mount the EFI partition. For CloudReady images it is /dev/sdX27, not sure what it is for other images, but it is usually the last numbered partition.

Then you can find your file in /efi/boot/ of the mounted partition. The simplest way is to rename the file to bootx64.efi and replace that.

**Comment by JiniMaster** [comment]
thanks, that helped!
the efi partition wasn't listed using "ls /dev/sdb*" but using "parted /dev/sdb print" showed the "missing" (GPT) partitions... 
then i was able to mount it and place the efi file there...
